### ISSUE TITLE
Max. number of function evaluations reached

### ISSUE THREAD

**Issue by zy-ke** [popgenmethods/momi2#12]
Hi,
I am using momi2 to infer demography of three populations. I have 37 samples from 10 populations in total in each vcf file and I just took three populations to infer a demography.
`model = momi.DemographicModel(
    N_e=1.2e4, gen_time=25, muts_per_gen=1.84e-8)
model.set_data(sfs)`
I added 7 parameters to be estimated: 
`model.add_size_param("n_pop1")`
`model.add_size_param("n_pop2")`
`model.add_size_param('n_pop3')`
`model.add_size_param("n_pop1_pop2)")`
`model.add_size_param("n_pop3_pop2")`
`model.add_time_param("t_pop1_pop2")`
`model.add_time_param("t_pop3_pop2")`
`model.add_leaf("pop1",N="n_pop1")`
`model.add_leaf("pop2",N="n_pop2")`
`model.add_leaf("pop3",N="n_pop3")`
`model.move_lineages("pop1","pop2",t="t_pop1_pop2",N="n_pop1_pop2")`
`model.move_lineages("pop3","pop2",t="t_pop3_pop2",N="n_pop3_pop2")`
`model.optimize(method="TNC")`

 I ran the analysis for several times but the values of parameters estimated changed a lot and I often got the message: "Max. number of function evaluations reached."
I was wondering if these are too many parameters to estimate and how could I avoid that message?

Thanks in advance,
Ziying

**Comment by jackkamm** [comment]
This means the optimizer is failing to converge. Maybe you need to run it for longer, or maybe the model is just too difficult to infer from the data, either due to the number of parameters or the graph structure of the demography.

Things you can try:
1) Increasing the number of iterations:
```
model.optimize(options={'maxiter':10000})
```
2) Reducing the number of parameters to estimate.

**Comment by zy-ke** [comment]
That is very helpful. Thanks a lot.
