### ISSUE TITLE
Can the current momi2 run on multiple compute nodes?

### ISSUE THREAD

**Issue by lsuhpchelp** [popgenmethods/momi2#16]
Dear momi2 developers,
I am from the user support group of a supercomputer cluster.  
Your tutorial at https://momi2.readthedocs.io/en/latest/parallel.html says "momi will automatically use all available CPUs to perform computations in parallel." Now one of our users needs to run momi2 on multiple compute nodes. So I wish to know if the current momi2 can run on multiple compute nodes. Many thanks. Please let me know if you need more info about our cluster environment. 
Best,

Yuwu

**Comment by jackkamm** [comment]
momi2 will use all available CPUs on a single compute node, but does not have support for using CPUs across multiple compute nodes.
