### ISSUE TITLE
Getting unique config array for subset of populations 

### ISSUE THREAD

**Issue by grafau** [popgenmethods/momi2#17]
Hi there,

Depending on what I got right from documentation this would be a feature request or bug report.

I would like to be able to extract 2d-SFS from my Nd-SFS. (2d-SFS plotting would be amazing too!). To do that, I need counts in all unique configs for given two populations. I cannot simply slice the config array for N populations, because there will be duplicates of configs rather than their sums.

It seems that right now the only way to get 2d-SFS is by creating new snpAlleleCounts for just two populations and then extracting sfs. It would be very convenient to be able to extract 2d-SFS directly from Nd-SFS, for example by using 'momi.extract_sfs' or 'momi.Sfs.load'. I tried using 'momi.site_freq_spectrum', giving it a list of populations and sfs.config-array in the following fashion:

`Tdsfs = momi.site_freq_spectrum(["LAO","KOR"], sfs.config_array , length=None)`

But sadly got following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-b3bf79b2c0dc> in <module>
----> 1 Tdsfs = momi.site_freq_spectrum(sfs.populations, sfs.config_array , length=None)

~/lib/python3.6/site-packages/momi/data/sfs.py in site_freq_spectrum(sampled_pops, freqs_by_locus, length)
     49 
     50     compressed_counts = CompressedAlleleCounts.from_iter(
---> 51         chained_sequences(), len(sampled_pops))
     52     config_array = compressed_counts.config_array
     53     index2uniq = compressed_counts.index2uniq

~/lib/python3.6/site-packages/momi/data/compressed_counts.py in from_iter(cls, config_iter, npops, sort)
     99         compressed_hashes = _CompressedHashedCounts(npops)
    100         for config in config_iter:
--> 101             compressed_hashes.append(config)
    102         return cls(compressed_hashes.config_array(),
    103                    compressed_hashes.index2uniq(),

~/lib/python3.6/site-packages/momi/data/compressed_counts.py in append(self, config)
     74 
     75     def append(self, config):
---> 76         self.compressed_list.append(_config2hashable(config))
     77 
     78     def index2uniq(self, i=None):

~/lib/python3.6/site-packages/momi/data/compressed_counts.py in _config2hashable(config)
      8 # (this seems to be more memory efficient than representing it as a tuple)
      9 def _config2hashable(config):
---> 10     return "\t".join("%d,%d" % (a, d) for a, d in config)
     11 
     12 

~/lib/python3.6/site-packages/momi/data/compressed_counts.py in <genexpr>(.0)
      8 # (this seems to be more memory efficient than representing it as a tuple)
      9 def _config2hashable(config):
---> 10     return "\t".join("%d,%d" % (a, d) for a, d in config)
     11 
     12 

TypeError: 'numpy.int64' object is not iterable
```

**Comment by grafau** [comment]
Update,

Ok, I found sfs.subset_populations, while it seem to extract only unique configs, it doesn't provide counts for them.

`Tdsfs = sfs.subset_populations(["LAO", "KOR"])`

Sorry, I didn't seesfs.subset_populations in the "latest" documentation: https://media.readthedocs.org/pdf/momi2/latest/momi2.pdf
https://momi2.readthedocs.io/en/latest/api.html

Is there any place where updated documentation can be found?

Many thanks!

**Comment by jackkamm** [comment]
Currently this method is undocumented, but it should be. I will leave this issue open until I have added the documentation for it.

**Comment by jackkamm** [comment]
I've added the documentation here:
https://momi2.readthedocs.io/en/latest/api.html#momi.Sfs.subset_populations
This method returns the lower-dimensional SFS restricted to the subset of specified populations.
