### ISSUE TITLE
How momi2 deals with strong bottleneck(s)

### ISSUE THREAD

**Issue by oushujun** [popgenmethods/momi2#18]
Hello,

Thanks for developing `momi2` that incorporates population admixtures for demographic inference. 

The species I work on experienced two very strong bottlenecks in the past 10,000 generations. The first bottleneck dropped Ne to ~0.1% (10,000 generations ago), the second bottleneck further dropped Ne to 30% (2,000 generations ago). Ne history of single populations was estimated using `smc++`.

I tried to estimate population splits using `smc++` after identifying and removing admixture regions, but results seem to reflect the two bottlenecks, with estimates of split either around 10K generations ago or around 2K generations ago.

Under these circumstances, could `momi2` correctly estimate population splits in consideration of strong introgressions and bottlenecks?

Thank you,
Shujun

**Comment by jackkamm** [comment]
momi2 could certainly fit a model with splits, strong introgressions, and bottlenecks. Whether there is enough power from the SFS to infer the true parameters would need to be tested with simulations.

**Comment by oushujun** [comment]
Thanks for your reply. I read the paper, but have not gone through the tutorial yet. Should the general process follow point estimation then parametric bootstrapping (simulations)?

**Comment by jackkamm** [comment]
Yes, though I recommend nonparametric bootstrapping over parametric; but it is good to do both. The tutorial has an example of nonparametric bootstrapping.

**Comment by oushujun** [comment]
Thank you very much for the advice. It's very attempting to try out this method.

Best,
Shujun
