### ISSUE TITLE
No valid SNPs read

### ISSUE THREAD

**Issue by aylwyn** [popgenmethods/momi2#2]
I'm getting 'No valid SNPs read! Try setting ancestral_alleles=False' using read_vcf, despite setting --no_aa . It's probably something to do with the vcf I have, but any other things I should check before starting to hack read_vcf?

**Comment by jackkamm** [comment]
Nothing immediate comes to mind. I rarely use folded SFS from VCF, I will write a unit test to check it's working. In mean time, if you have a minimal VCF you can provide that could be helpful.

**Comment by aylwyn** [comment]
Ok will do. Re folded SFS, I could provide a distant outgroup or inferred ancestral state but it might not be terribly accurate for these data, particularly at mutable sites. So wanted to see how it performed first without one.

**Comment by jackkamm** [comment]
Reading VCF without AA seems to work fine for me -- just pushed a unit test to "develop" branch testing the Python API and I also manually checked the command line API as well.

**Comment by aylwyn** [comment]
Ok after further testing I think the problem is my bed file as it runs when I don't specify one. Should the bed specify callable or uncallable regions?

**Comment by jackkamm** [comment]
The BED file is supposed to specify callable regions.

**Comment by aylwyn** [comment]
Ok that seems to have fixed the error :) Might be good to update the documentation to make that explicit.

**Comment by jackkamm** [comment]
Thanks for the feedback; I have updated the docs to clarify the usage of BED files.
