### ISSUE TITLE
Multithreading control?

### ISSUE THREAD

**Issue by grafau** [popgenmethods/momi2#20]
momi2 seems to be quite liberal with taking a lot of cores and I was wondering if there is/will be any way to control how many threads it runs?

Many thanks!

**Comment by terhorst** [comment]
Please see [docs/parallel.rst](https://github.com/popgenmethods/momi2/blob/master/docs/parallel.rst).

**Comment by grafau** [comment]
Thanks! I am not sure if I asked the right question then.

I am doing the following in ipython:

%env OMP_NUM_THREADS=24                                                                                                                                                                                                                                                                                                                                            
env: OMP_NUM_THREADS=24

model.optimize(method="TNC") 

But it still uses up on average 5000% CPU. Is there a way to control number of CPUs used?

Thanks!
