### ISSUE TITLE
Ghost population necessary for an introgression model?

### ISSUE THREAD

**Issue by oushujun** [popgenmethods/momi2#21]
Hello,

I want to use momi2 to estimate introgression time and pulse size, in the tutorial, I saw a ghost NEA population was introduced as the admixture donor, is this ghost population necessary? Can I directly use the current population as a donor for introgression estimations?

Thanks,
Shujun

**Comment by jackkamm** [comment]
No, a ghost population was not necessary, the example was simply to demonstrate that momi2 can handle ghost populations. Feel free to add a direct pulse without a ghost.
