### ISSUE TITLE
Estimating migration Kernel has died

### ISSUE THREAD

**Issue by isisarantes** [popgenmethods/momi2#24]
I'm not sure why it is happening but when I try to estimate migration between 3 populations, the kernel dies.
I'm using it in the HPC and using a lot of memory and 8 ncpus.
Any idea?
Best, 
Ísis
![screen shot 2019-02-18 at 10 15 22 am](https://user-images.githubusercontent.com/10964418/52964597-4ba17a80-3368-11e9-8f4d-174e81549662.png)

**Comment by terhorst** [comment]
An error message should be printed to the console which could help us debug further.

**Comment by isisarantes** [comment]
<img width="1274" alt="screen shot 2019-02-18 at 10 42 20 am" src="https://user-images.githubusercontent.com/10964418/52965234-f6feff00-3369-11e9-8347-cc83edb8e3be.png">
<img width="909" alt="screen shot 2019-02-18 at 10 41 55 am" src="https://user-images.githubusercontent.com/10964418/52965235-f6feff00-3369-11e9-994a-2a0f1edf271d.png">
I get this from my terminal window and my momi log. I Using the funcition migration_model.optimize() and it seems to be the issues to me, because it runs fast without using this function.

**Comment by isisarantes** [comment]
I don't get any error message using jupyter notebook, I get the message that my Kernel has died. I don't understand why. I just started using momi2.

**Comment by jackkamm** [comment]
Can you try exporting the notebook to a Python script (via `jupyter nbconvert` or dropdown menu) and running that? It may give a better error message.

Also, how many samples do you have in your 3 populations? Does the same problem occur if you decrease the sample size?

**Comment by isisarantes** [comment]
I know the issue, I'm doing a bad job writing the code and for some reason makes the kernel die when I use the model.optimize () function. If I don't use the function it gives me the error message with what I'm writing wrong. I'm having a really hard time trying to understand the tutorial and the documentation. The examples are complicated (at least form me) and when I'm trying to look for information about the particular function and the parameters, I can't find enough info. I know a little of python and a lot of R, and maybe my lack of knowledge on python is making it so difficult.
So, this is what I'm trying to run: 
 I have 3 populations (115 samples, 63 central, 36 south, and 16 north) and I don't know the time of divergence, the population size, migration, and the mutation rate. I'm trying to estimate it all using momi2. I know that my ancestral population is the central population of north and south.  I'm trying to follow the tutorial from RADcamp that uses 2 populations, and looks so easy and simple to estimate the divergence, pop size, migration. But when I try to add the 3rd population, it starts to get complicated. I don't know how to make it work. If you have any tips, please let me know. Thank you,

**Comment by isisarantes** [comment]
I figured it out to write code correctly. Phew! But I'm having issues when I try to run the bootstrap and the model optimize function. I reduced my dataset to less than half number of samples now but the these functions are taking a lot of time to run in the HPC. I was wondering if I should do some kinda of filtering of the data, any suggestion?  Thank you,
