### ISSUE TITLE
ImportError: /miniconda3/lib/python3.6/site-packages/../../libgsl.so.23: undefined symbol: cblas_dasum

### ISSUE THREAD

**Issue by kevinmneal** [popgenmethods/momi2#25]
Hi,

I keep encountering this issue when I try to run the program. Googling the issue hasn't yielded much help, so I wonder if anyone here might have any insights into the problem. If it helps, I did NOT install in a separate environment like the tutorial does, and I installed using miniconda3.

`python -m momi.read_vcf
Traceback (most recent call last):
  File "/home/kevin/miniconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/kevin/miniconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/kevin/miniconda3/lib/python3.6/site-packages/momi/__init__.py", line 8, in <module>
    from .likelihood import SfsLikelihoodSurface
  File "/home/kevin/miniconda3/lib/python3.6/site-packages/momi/likelihood.py", line 11, in <module>
    from .demography import Demography
  File "/home/kevin/miniconda3/lib/python3.6/site-packages/momi/demography.py", line 8, in <module>
    import msprime
  File "/home/kevin/miniconda3/lib/python3.6/site-packages/msprime/__init__.py", line 26, in <module>
    from _msprime import FORWARD  # NOQA
ImportError: /home/kevin/miniconda3/lib/python3.6/site-packages/../../libgsl.so.23: undefined symbol: cblas_dasum`

**Comment by kevinmneal** [comment]
After some digging, the issue was with msprime. When I followed the commands to install momi2, it seems only msprime 0.6.1 was installed. Issue seems fixed when ensuring it's updated to 0.6.2 via ` conda install -c conda-forge msprime `

More info here: https://github.com/conda-forge/msprime-feedstock/issues/20

**Comment by didier-aurelle** [comment]
Hi
I apparently have the same error when trying to run momi2:
ImportError: /home/aurelle/anaconda3/envs/momi_py36/lib/python3.6/site-packages/../../libgsl.so.23: undefined symbol: cblas_dasum
I installed msprime again but it still doesn't work
thanks

**Comment by terhorst** [comment]
From the discussions linked above, it's due to having mismatching / multiple BLAS libraries installed. It's not something we can address in momi2.

**Comment by jackkamm** [comment]
Maybe bumping the msprime version requirement to 0.6.2 or 0.7.0 would help?

@didier-aurelle can you show your msprime version with 
```
conda list | grep msprime
```

**Comment by didier-aurelle** [comment]
Hi, here is what I get:
msprime                   0.7.0            py36h1f597ea_1    conda-forge
apparently I have the right version
but as an update, I can now import momi from Python in my bash shell, but I can't do it (same error as above) from my jupyter notebook...
Didier

**Comment by terhorst** [comment]
Can you paste the output of `which jupyter`?

**Comment by didier-aurelle** [comment]
here it is:
/home/aurelle/anaconda3/bin/jupyter
but apparently I found a solution: new installation from jupyter and it works
thanks
