### ISSUE TITLE
Inconsistent log likelihood

### ISSUE THREAD

**Issue by chanjed** [popgenmethods/momi2#3]
If I understand correctly the standard optimization method `model.optimize(method='TNC')` returns the negative log likelihood while SGD `model.stochastic_optimize(snps_per_minibatch=1000, num_iters=10, svrg_epoch=3)` returns the negative log likelihood which is a bit confusing unless I am misunderstanding the values that are returned under the log_likelihood parameter.

**Comment by jackkamm** [comment]
Sorry for not responding to this for so long. You're right, the `log_likelihood` entry in the result returned by `stochastic_optimize` is misnamed. I renamed that field to `cross_entropy` instead.
