### ISSUE TITLE
Support networkx 2.4+

### ISSUE THREAD

**Issue by jackkamm** [popgenmethods/momi2#33]
networkx 2.4 introduces breaking changes (DiGraph.node no longer exists)

**Comment by kepra3** [comment]
Is there a solution to this issue?

**Comment by alanaw1** [comment]
Hi @kepra3, I raised the same issue as you did, and found a solution to it. I've described it in #38, in case you're still interested!

**Comment by isaacovercast** [comment]
@alanaw1 Thanks for the solution. +1. I just ran into this again. Happy to make a pr if there's a general sense of how tricky this will be to fix.

**Comment by jackkamm** [comment]
Sorry for the delay all. I've fixed this issue in the most recent commit.
