### ISSUE TITLE
ongoing migration

### ISSUE THREAD

**Issue by glaudelrio** [popgenmethods/momi2#42]
I would like to know whether momi2 allows setting up demographic models with ongoing gene flow. I am confused with the idea of being able to estimate migration only in the form of pulses of migration.
Thank you so much for any help!
Best wishes

**Comment by glaudelrio** [comment]
Also, I would like to know if inputing a VCF with minimum allele count of 3 will somehow affect SFS in a way that model comparisons are hindered.

**Comment by jackkamm** [comment]
momi2 does not support continuous gene flow, it is a limitation of the method.

momi is able to compute the likelihood of a model with 3 alleles, but whether the model parameters converge depends on the specific demographic model.
