### ISSUE TITLE
Unable to install it

### ISSUE THREAD

**Issue by huanglei15** [popgenmethods/momi2#43]
I installed Miniconda3-py37_4.9.2-Linux-x86_64.sh in the virtual machine and ran "conda install -c jackkamm momi" in the terminal. It went like that

(base) lsda@lsdabox:~$ conda install -c jackkamm momi
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

I didn't do anything else. Maybe it's a problem in the environment settings in miniconda? Currently I don't know why.

**Comment by jackkamm** [comment]
It looks like the install command is incorrect, it should be:
```
conda install momi -c conda-forge -c bioconda -c jackkamm
```
See also: https://momi2.readthedocs.io/en/latest/installation.html

**Comment by huanglei15** [comment]
![image](https://user-images.githubusercontent.com/56875428/113338091-f1d25380-9328-11eb-8419-2509084d5884.png)
Thanks. Now I could install and run it. But the command I once used is from the picture. (Someone sent me but I don't know where it's from.) Do you think it's correct?

**Comment by jackkamm** [comment]
It's from https://anaconda.org/jackkamm/momi. However, it's autogenerated by anaconda.org and I don't think there's any way for me to change it. If you find a way to do so, please reopen this issue.
