### ISSUE TITLE
plotting issue

### ISSUE THREAD

**Issue by XuexueLiu** [popgenmethods/momi2#44]
Hello Jack
I follow the tutorial, but has a problem for plotting:
# plot the model
    ...: fig = momi.DemographyPlot(no_pulse_model, ["YRI", "CHB"],
    ...:                           figsize=(6,8), linthreshy=1e5,
    ...:                           major_yticks=yticks,
    ...:                           pulse_color_bounds=(0,.25))
/disk/anaconda3/lib/python3.8/site-packages/momi/demo_plotter.py:69: MatplotlibDeprecationWarning: The 'linthreshy' parameter of __init__() has been renamed 'linthresh' since Matplotlib 3.3; support for the old name will be dropped two minor releases later.
  self.ax.set_yscale('symlog', linthreshy=linthreshy)

is there any solutions for this?
thankyou
Xue

**Comment by jackkamm** [comment]
Thank you for reporting this, and sorry for the very delayed response.

I've updated the master branch to use the renamed matplotlib parameter internally, and this fix will be included in the next momi2 release, coming soon.
