### ISSUE TITLE
Guidance on pronunciation

### ISSUE THREAD

**Issue by isaacovercast** [popgenmethods/momi2#6]
I'm really pleased with momi2. The API mode and the tutorial are both really cool and useful. Unfortunately, there's a raging debate in a corner of the NYC popgen community over how to pronounce 'momi'. It's getting ugly, and i'm hoping to resolve it once and for all by soliciting input from the developer. I'm rooting for 'mommy', but some people insist on calling it 'moe-me'. Thoughts?

**Comment by terhorst** [comment]
How do you pronounce ∂a∂i? ;-)

**Comment by isaacovercast** [comment]
Lol. Best possible answer.

**Comment by jackkamm** [comment]
Both pronunciations are valid, but I personally say "mommy"
