### ISSUE TITLE
No BED provided, will need to specify length manually with mutation rate

### ISSUE THREAD

**Issue by XiaXiaTianTian** [popgenmethods/momi2#65]
Hi all,
When I use `/ds3200_1/proc/anaconda3/bin/python -m momi.read_vcf --outgroup B all.vcf.gz  ind_pop.list  momi2.gz`. I got the result, but at the same time I got the error `No BED provided, will need to specify length manually with mutation rate`.
Will there be any bad errors for  the subsequent steps if I just use this result? 

Thank you all.

**Comment by jackkamm** [comment]
It is just a warning, and there shouldn't be any errors.

If you want, you can instead specify the genome size by using the `length` parameter in [DemographicModel.set_data](https://momi2.readthedocs.io/en/latest/api.html#momi.DemographicModel.set_data).

Alternatively, momi2 can perform inference without knowing the genome size or mutation rate -- though it may affect power or identifiability, depending on the model parametrization.

**Comment by XiaXiaTianTian** [comment]
I tried.
Thank you so much.
