### ISSUE TITLE
move_lineages population order

### ISSUE THREAD

**Issue by cjbattey** [popgenmethods/momi2#8]
Hi, 
The API documentation for move_lineages lists the order of populations as (from,to), but demography plots display an arrow moving in the opposite direction. The use in the tutorial also seems to be (to,from). Is the documentation backwards or am I confused about something? 

Very cool piece of software btw - thanks for making it available. 

CJ

**Comment by isaacovercast** [comment]
The move lineages operation is backwards in time (coalescent), but the plot shows the forward in time direction probably because this is more natural for people to interpret visually.
