### ISSUE TITLE
bug in Sfs.fold()

### ISSUE THREAD

**Issue by isaacovercast** [popgenmethods/momi2#9]
I think the folded sfs is not being calculated accurately. Inside momi.Sfs.fold is a subfunction called `get_folded()` which is doing elementwise comparison of config tuples:
```
        def get_folded(config):
            if tuple(config[:, 0]) < tuple(config[:, 1]):
                return config[:, ::-1]
            else:
                return config
```
Elementwise tuple comparison like this is lazy, in the sense that if any comparison evaluates to True, then the expression evaluates to True, whereas what I think is desired here is for _all_ elementwise comparisons to evaluate as True for the `<`, so something like this:
```
            if np.all(np.array(config[:, 0]) < np.array(config[:, 1])):
```
The net results is that some configs will be folded when I believe they shouldn't be. For example `[[3, 5], [8, 0]]` will be turned into `[[5, 3], [0, 8]]`.

I could be way off base here, but I came across this because i'm writing a dadi-style sfs to momi-style sfs converter, and the unfolded sfs conversion worked flawlessly, but the folded conversion kept giving me inconsistent results and it was driving me nuts! Working on a PR...

**Comment by jackkamm** [comment]
How come it's wrong to map ((3,5),(8,0)) to ((5,3),(0,8))?

In the folded SFS these two configs are equivalent, but which one is the canonical one is more or less arbitrary, as long as we are consistent. Right now the convention is that the allele with "smaller" counts tuple (according to Python tuple comparison) is the 0 allele. Do you think there is some other convention we should follow?

In Python, tuple comparison is alphabetical, so the first entry where the 2 tuples disagree will determine which is lesser -- it's not the case that any comparison evaluating to True will cause the expression to evaluate to True.

**Comment by isaacovercast** [comment]
Ah, I see, that makes sense. Sorry, I was a little confused because the way dadi performs the folding is different, more analogous to something like this:
```
if np.sum(config[:, 1]) > np.sum(self.sampled_n)/2.:
    return config[:, ::-1]
```
The way you're doing it is clever, and I don't think it's a good idea to change to the dadi way. This choice of how to fold configs will complicate conversion from the dadi format, but this is an edge case. I'll figure it out and build it into the dadi->momi sfs conversion script. Thanks for the clarification.
